version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - microservices-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - microservices-network

#  rabbitmq:
#    image: rabbitmq:3.13-management
#    container_name: rabbitmq
#    restart: unless-stopped
#    ports:
#      - "5672:5672"   # AMQP port
#      - "15672:15672" # Management UI port
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: password123
#      RABBITMQ_DEFAULT_VHOST: /
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#      - rabbitmq_logs:/var/log/rabbitmq
#    networks:
#      - microservices-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  microservices-network:
    driver: bridge